#!/bin/sh
#
# RC sets up the system (multi-user)
#

# Make nodes
echo 'creating device nodes'
mknod /dev/null c 3 0
mknod /dev/random c 4 0
cat /dev/null >/etc/utmp
touch /etc/mount /dev/rp3

echo 'clearing /tmp'
rm -rf /tmp/
mkdir /tmp

# default syslog logging file
mkdir -p /var/log/
touch /var/log/system.log

echo 'updating motd'
echo -n "Welcome to FreeNIX version " > /etc/motd
uname -r >> /etc/motd

echo -n 'starting daemons:'
# System daemons go here.
echo '.'

sh /etc/rc.local

echo; banner FreeNIX

echo "The system is up and running. Root account password is 'root',"
echo "or feel free to login as a guest."

