// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_read    5
#define SYS_kill    6
#define SYS_exec    7
#define SYS_fstat   8
#define SYS_chdir   9
#define SYS_dup    10
#define SYS_getpid 11
#define SYS_sbrk   12
#define SYS_sleep  13
#define SYS_uptime 14
#define SYS_open   15
#define SYS_write  16
#define SYS_mknod  17
#define SYS_unlink 18
#define SYS_link   19
#define SYS_mkdir  20
#define SYS_close  21
#define SYS_getuid 22
#define SYS_getgid 23
#define SYS_setuid 24
#define SYS_setgid 25
#define SYS_usleep 26
#define SYS_time   27
#define SYS_uname  28
#define SYS_sync   29
#define SYS_stty   30
#define SYS_lseek  31
#define SYS_devctl 32
#define SYS_stime  33
#define SYS_utime  34
#define SYS_sethostname 35
#define SYS_setenv 36
#define SYS_secure_getenv 37
#define SYS_environ 38
